// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const clearBillingUsage = `-- name: ClearBillingUsage :exec
DELETE FROM billing_usage
`

func (q *Queries) ClearBillingUsage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearBillingUsage)
	return err
}

const clearJobs = `-- name: ClearJobs :exec
DELETE FROM jobs
`

func (q *Queries) ClearJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearJobs)
	return err
}

const clearRepos = `-- name: ClearRepos :exec
DELETE FROM repos
`

func (q *Queries) ClearRepos(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRepos)
	return err
}

const clearRuns = `-- name: ClearRuns :exec
DELETE FROM runs
`

func (q *Queries) ClearRuns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRuns)
	return err
}

const listBillingUsage = `-- name: ListBillingUsage :many
SELECT
    CAST(coalesce("key", '') AS text) AS "key",
    CAST(coalesce(account, '') AS text) AS account,
    CAST(coalesce(account_kind, '') AS text) AS account_kind,
    CAST(coalesce(date, '') AS text) AS date,
    CAST(coalesce(year, 0) AS integer) AS year,
    CAST(coalesce(month, 0) AS integer) AS month,
    CAST(coalesce(day, 0) AS integer) AS day,
    CAST(coalesce(product, '') AS text) AS product,
    CAST(coalesce(sku, '') AS text) AS sku,
    CAST(coalesce(unit_type, '') AS text) AS unit_type,
    CAST(coalesce(model, '') AS text) AS model,
    CAST(coalesce(organization_name, '') AS text) AS organization_name,
    CAST(coalesce(repository_name, '') AS text) AS repository_name,
    CAST(coalesce(cost_center_id, '') AS text) AS cost_center_id,
    CAST(coalesce(cost_class, '') AS text) AS cost_class,
    CAST(coalesce(quantity, 0) AS real) AS quantity,
    CAST(coalesce(gross_quantity, 0) AS real) AS gross_quantity,
    CAST(coalesce(discount_quantity, 0) AS real) AS discount_quantity,
    CAST(coalesce(net_quantity, 0) AS real) AS net_quantity,
    CAST(coalesce(price_per_unit, 0) AS real) AS price_per_unit,
    CAST(coalesce(gross_amount, 0) AS real) AS gross_amount,
    CAST(coalesce(discount_amount, 0) AS real) AS discount_amount,
    CAST(coalesce(net_amount, 0) AS real) AS net_amount,
    CAST(coalesce(raw_json, '') AS text) AS raw_json
FROM billing_usage
WHERE (CAST(?1 AS integer) = 0 OR account = ?2)
    AND (CAST(?3 AS integer) = 0 OR repository_name = ?4)
    AND (CAST(?5 AS integer) = 0 OR date >= ?6)
    AND (CAST(?7 AS integer) = 0 OR date <= ?8)
    AND (CAST(?9 AS integer) = 0 OR year = ?10)
    AND (CAST(?11 AS integer) = 0 OR month = ?12)
    AND (CAST(?13 AS integer) = 0 OR day = ?14)
    AND (CAST(?15 AS integer) = 0 OR product = ?16)
    AND (CAST(?17 AS integer) = 0 OR sku = ?18)
    AND (CAST(?19 AS integer) = 0 OR organization_name = ?20)
    AND (CAST(?21 AS integer) = 0 OR cost_center_id = ?22)
ORDER BY net_amount DESC, date DESC
LIMIT CAST(?23 AS integer)
`

type ListBillingUsageParams struct {
	FilterAccount      int64
	Account            sql.NullString
	FilterRepo         int64
	Repo               sql.NullString
	FilterSince        int64
	Since              sql.NullString
	FilterUntil        int64
	Until              sql.NullString
	FilterYear         int64
	Year               sql.NullInt64
	FilterMonth        int64
	Month              sql.NullInt64
	FilterDay          int64
	Day                sql.NullInt64
	FilterProduct      int64
	Product            sql.NullString
	FilterSKU          int64
	SKU                sql.NullString
	FilterOrganization int64
	Organization       sql.NullString
	FilterCostCenterID int64
	CostCenterID       sql.NullString
	Limit              int64
}

type ListBillingUsageRow struct {
	Key              string
	Account          string
	AccountKind      string
	Date             string
	Year             int64
	Month            int64
	Day              int64
	Product          string
	SKU              string
	UnitType         string
	Model            string
	OrganizationName string
	RepositoryName   string
	CostCenterID     string
	CostClass        string
	Quantity         float64
	GrossQuantity    float64
	DiscountQuantity float64
	NetQuantity      float64
	PricePerUnit     float64
	GrossAmount      float64
	DiscountAmount   float64
	NetAmount        float64
	RawJSON          string
}

func (q *Queries) ListBillingUsage(ctx context.Context, arg ListBillingUsageParams) ([]ListBillingUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, listBillingUsage,
		arg.FilterAccount,
		arg.Account,
		arg.FilterRepo,
		arg.Repo,
		arg.FilterSince,
		arg.Since,
		arg.FilterUntil,
		arg.Until,
		arg.FilterYear,
		arg.Year,
		arg.FilterMonth,
		arg.Month,
		arg.FilterDay,
		arg.Day,
		arg.FilterProduct,
		arg.Product,
		arg.FilterSKU,
		arg.SKU,
		arg.FilterOrganization,
		arg.Organization,
		arg.FilterCostCenterID,
		arg.CostCenterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillingUsageRow{}
	for rows.Next() {
		var i ListBillingUsageRow
		if err := rows.Scan(
			&i.Key,
			&i.Account,
			&i.AccountKind,
			&i.Date,
			&i.Year,
			&i.Month,
			&i.Day,
			&i.Product,
			&i.SKU,
			&i.UnitType,
			&i.Model,
			&i.OrganizationName,
			&i.RepositoryName,
			&i.CostCenterID,
			&i.CostClass,
			&i.Quantity,
			&i.GrossQuantity,
			&i.DiscountQuantity,
			&i.NetQuantity,
			&i.PricePerUnit,
			&i.GrossAmount,
			&i.DiscountAmount,
			&i.NetAmount,
			&i.RawJSON,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT
    CAST(coalesce(id, 0) AS integer) AS id,
    CAST(coalesce(run_id, 0) AS integer) AS run_id,
    CAST(coalesce(account, '') AS text) AS account,
    CAST(coalesce(repo, '') AS text) AS repo,
    CAST(coalesce(repo_owner, '') AS text) AS repo_owner,
    CAST(coalesce(repo_owner_kind, '') AS text) AS repo_owner_kind,
    CAST(coalesce(billing_owner, '') AS text) AS billing_owner,
    CAST(coalesce(billing_owner_kind, '') AS text) AS billing_owner_kind,
    CAST(coalesce(billing_plan, '') AS text) AS billing_plan,
    CAST(coalesce(cost_class, '') AS text) AS cost_class,
    CAST(coalesce(workflow_name, '') AS text) AS workflow_name,
    CAST(coalesce(workflow_path, '') AS text) AS workflow_path,
    CAST(coalesce(name, '') AS text) AS name,
    CAST(coalesce(status, '') AS text) AS status,
    CAST(coalesce(conclusion, '') AS text) AS conclusion,
    CAST(coalesce(started_at, '') AS text) AS started_at,
    CAST(coalesce(completed_at, '') AS text) AS completed_at,
    CAST(coalesce(duration_seconds, 0) AS real) AS duration_seconds,
    CAST(coalesce(runner_name, '') AS text) AS runner_name,
    CAST(coalesce(runner_group, '') AS text) AS runner_group,
    CAST(coalesce(runner_type, '') AS text) AS runner_type,
    CAST(coalesce(runner_os, '') AS text) AS runner_os,
    CAST(coalesce(runner_arch, '') AS text) AS runner_arch,
    CAST(coalesce(runner_image, '') AS text) AS runner_image,
    CAST(coalesce(labels_json, '[]') AS text) AS labels_json,
    CAST(coalesce(html_url, '') AS text) AS html_url,
    CAST(coalesce(raw_json, '') AS text) AS raw_json
FROM jobs
WHERE (CAST(?1 AS integer) = 0 OR repo = ?2)
    AND (CAST(?3 AS integer) = 0 OR started_at >= ?4)
    AND (CAST(?5 AS integer) = 0 OR started_at <= ?6)
ORDER BY duration_seconds DESC, started_at DESC
LIMIT CAST(?7 AS integer)
`

type ListJobsParams struct {
	FilterRepo  int64
	Repo        sql.NullString
	FilterSince int64
	Since       sql.NullString
	FilterUntil int64
	Until       sql.NullString
	Limit       int64
}

type ListJobsRow struct {
	ID               int64
	RunID            int64
	Account          string
	Repo             string
	RepoOwner        string
	RepoOwnerKind    string
	BillingOwner     string
	BillingOwnerKind string
	BillingPlan      string
	CostClass        string
	WorkflowName     string
	WorkflowPath     string
	Name             string
	Status           string
	Conclusion       string
	StartedAt        string
	CompletedAt      string
	DurationSeconds  float64
	RunnerName       string
	RunnerGroup      string
	RunnerType       string
	RunnerOS         string
	RunnerArch       string
	RunnerImage      string
	LabelsJSON       string
	HtmlURL          string
	RawJSON          string
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobs,
		arg.FilterRepo,
		arg.Repo,
		arg.FilterSince,
		arg.Since,
		arg.FilterUntil,
		arg.Until,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Account,
			&i.Repo,
			&i.RepoOwner,
			&i.RepoOwnerKind,
			&i.BillingOwner,
			&i.BillingOwnerKind,
			&i.BillingPlan,
			&i.CostClass,
			&i.WorkflowName,
			&i.WorkflowPath,
			&i.Name,
			&i.Status,
			&i.Conclusion,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationSeconds,
			&i.RunnerName,
			&i.RunnerGroup,
			&i.RunnerType,
			&i.RunnerOS,
			&i.RunnerArch,
			&i.RunnerImage,
			&i.LabelsJSON,
			&i.HtmlURL,
			&i.RawJSON,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT
    CAST(coalesce(id, 0) AS integer) AS id,
    CAST(coalesce(account, '') AS text) AS account,
    CAST(coalesce(owner, '') AS text) AS owner,
    CAST(coalesce(owner_kind, '') AS text) AS owner_kind,
    CAST(coalesce(name, '') AS text) AS name,
    CAST(coalesce(full_name, '') AS text) AS full_name,
    CAST(coalesce(private, 0) AS integer) AS private,
    CAST(coalesce(billing_owner, '') AS text) AS billing_owner,
    CAST(coalesce(billing_owner_kind, '') AS text) AS billing_owner_kind,
    CAST(coalesce(billing_plan, '') AS text) AS billing_plan,
    CAST(coalesce(raw_json, '') AS text) AS raw_json
FROM repos
ORDER BY full_name
`

type ListReposRow struct {
	ID               int64
	Account          string
	Owner            string
	OwnerKind        string
	Name             string
	FullName         string
	Private          int64
	BillingOwner     string
	BillingOwnerKind string
	BillingPlan      string
	RawJSON          string
}

func (q *Queries) ListRepos(ctx context.Context) ([]ListReposRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReposRow{}
	for rows.Next() {
		var i ListReposRow
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Owner,
			&i.OwnerKind,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.BillingOwner,
			&i.BillingOwnerKind,
			&i.BillingPlan,
			&i.RawJSON,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT
    CAST(coalesce(id, 0) AS integer) AS id,
    CAST(coalesce(account, '') AS text) AS account,
    CAST(coalesce(repo, '') AS text) AS repo,
    CAST(coalesce(repo_owner, '') AS text) AS repo_owner,
    CAST(coalesce(repo_owner_kind, '') AS text) AS repo_owner_kind,
    CAST(coalesce(billing_owner, '') AS text) AS billing_owner,
    CAST(coalesce(billing_owner_kind, '') AS text) AS billing_owner_kind,
    CAST(coalesce(billing_plan, '') AS text) AS billing_plan,
    CAST(coalesce(workflow_id, 0) AS integer) AS workflow_id,
    CAST(coalesce(workflow_name, '') AS text) AS workflow_name,
    CAST(coalesce(workflow_path, '') AS text) AS workflow_path,
    CAST(coalesce(run_number, 0) AS integer) AS run_number,
    CAST(coalesce(run_attempt, 0) AS integer) AS run_attempt,
    CAST(coalesce(event, '') AS text) AS event,
    CAST(coalesce(branch, '') AS text) AS branch,
    CAST(coalesce(actor, '') AS text) AS actor,
    CAST(coalesce(status, '') AS text) AS status,
    CAST(coalesce(conclusion, '') AS text) AS conclusion,
    CAST(coalesce(created_at, '') AS text) AS created_at,
    CAST(coalesce(run_started_at, '') AS text) AS run_started_at,
    CAST(coalesce(html_url, '') AS text) AS html_url,
    CAST(coalesce(raw_json, '') AS text) AS raw_json
FROM runs
WHERE (CAST(?1 AS integer) = 0 OR repo = ?2)
    AND (CAST(?3 AS integer) = 0 OR run_started_at >= ?4)
    AND (CAST(?5 AS integer) = 0 OR run_started_at <= ?6)
ORDER BY run_started_at DESC
LIMIT CAST(?7 AS integer)
`

type ListRunsParams struct {
	FilterRepo  int64
	Repo        sql.NullString
	FilterSince int64
	Since       sql.NullString
	FilterUntil int64
	Until       sql.NullString
	Limit       int64
}

type ListRunsRow struct {
	ID               int64
	Account          string
	Repo             string
	RepoOwner        string
	RepoOwnerKind    string
	BillingOwner     string
	BillingOwnerKind string
	BillingPlan      string
	WorkflowID       int64
	WorkflowName     string
	WorkflowPath     string
	RunNumber        int64
	RunAttempt       int64
	Event            string
	Branch           string
	Actor            string
	Status           string
	Conclusion       string
	CreatedAt        string
	RunStartedAt     string
	HtmlURL          string
	RawJSON          string
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuns,
		arg.FilterRepo,
		arg.Repo,
		arg.FilterSince,
		arg.Since,
		arg.FilterUntil,
		arg.Until,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Repo,
			&i.RepoOwner,
			&i.RepoOwnerKind,
			&i.BillingOwner,
			&i.BillingOwnerKind,
			&i.BillingPlan,
			&i.WorkflowID,
			&i.WorkflowName,
			&i.WorkflowPath,
			&i.RunNumber,
			&i.RunAttempt,
			&i.Event,
			&i.Branch,
			&i.Actor,
			&i.Status,
			&i.Conclusion,
			&i.CreatedAt,
			&i.RunStartedAt,
			&i.HtmlURL,
			&i.RawJSON,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stats = `-- name: Stats :one
SELECT
    (SELECT count(*) FROM repos) AS repos,
    (SELECT count(*) FROM runs) AS runs,
    (SELECT count(*) FROM jobs) AS jobs,
    (SELECT count(*) FROM billing_usage) AS billing_usage
`

type StatsRow struct {
	Repos        int64
	Runs         int64
	Jobs         int64
	BillingUsage int64
}

func (q *Queries) Stats(ctx context.Context) (StatsRow, error) {
	row := q.db.QueryRowContext(ctx, stats)
	var i StatsRow
	err := row.Scan(
		&i.Repos,
		&i.Runs,
		&i.Jobs,
		&i.BillingUsage,
	)
	return i, err
}

const upsertBillingUsage = `-- name: UpsertBillingUsage :exec
INSERT INTO billing_usage("key", account, account_kind, date, year, month, day, product, sku, unit_type, model, organization_name, repository_name, cost_center_id, cost_class, quantity, gross_quantity, discount_quantity, net_quantity, price_per_unit, gross_amount, discount_amount, net_amount, raw_json, updated_at)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19,
    ?20,
    ?21,
    ?22,
    ?23,
    ?24,
    current_timestamp
)
ON CONFLICT("key") DO UPDATE SET
    account = excluded.account,
    account_kind = excluded.account_kind,
    date = excluded.date,
    year = excluded.year,
    month = excluded.month,
    day = excluded.day,
    product = excluded.product,
    sku = excluded.sku,
    unit_type = excluded.unit_type,
    model = excluded.model,
    organization_name = excluded.organization_name,
    repository_name = excluded.repository_name,
    cost_center_id = excluded.cost_center_id,
    cost_class = excluded.cost_class,
    quantity = excluded.quantity,
    gross_quantity = excluded.gross_quantity,
    discount_quantity = excluded.discount_quantity,
    net_quantity = excluded.net_quantity,
    price_per_unit = excluded.price_per_unit,
    gross_amount = excluded.gross_amount,
    discount_amount = excluded.discount_amount,
    net_amount = excluded.net_amount,
    raw_json = excluded.raw_json,
    updated_at = current_timestamp
`

type UpsertBillingUsageParams struct {
	Key              string
	Account          sql.NullString
	AccountKind      sql.NullString
	Date             sql.NullString
	Year             sql.NullInt64
	Month            sql.NullInt64
	Day              sql.NullInt64
	Product          sql.NullString
	SKU              sql.NullString
	UnitType         sql.NullString
	Model            sql.NullString
	OrganizationName sql.NullString
	RepositoryName   sql.NullString
	CostCenterID     sql.NullString
	CostClass        sql.NullString
	Quantity         sql.NullFloat64
	GrossQuantity    sql.NullFloat64
	DiscountQuantity sql.NullFloat64
	NetQuantity      sql.NullFloat64
	PricePerUnit     sql.NullFloat64
	GrossAmount      sql.NullFloat64
	DiscountAmount   sql.NullFloat64
	NetAmount        sql.NullFloat64
	RawJSON          sql.NullString
}

func (q *Queries) UpsertBillingUsage(ctx context.Context, arg UpsertBillingUsageParams) error {
	_, err := q.db.ExecContext(ctx, upsertBillingUsage,
		arg.Key,
		arg.Account,
		arg.AccountKind,
		arg.Date,
		arg.Year,
		arg.Month,
		arg.Day,
		arg.Product,
		arg.SKU,
		arg.UnitType,
		arg.Model,
		arg.OrganizationName,
		arg.RepositoryName,
		arg.CostCenterID,
		arg.CostClass,
		arg.Quantity,
		arg.GrossQuantity,
		arg.DiscountQuantity,
		arg.NetQuantity,
		arg.PricePerUnit,
		arg.GrossAmount,
		arg.DiscountAmount,
		arg.NetAmount,
		arg.RawJSON,
	)
	return err
}

const upsertJob = `-- name: UpsertJob :exec
INSERT INTO jobs(id, run_id, account, repo, repo_owner, repo_owner_kind, billing_owner, billing_owner_kind, billing_plan, cost_class, workflow_name, workflow_path, name, status, conclusion, started_at, completed_at, duration_seconds, runner_name, runner_group, runner_type, runner_os, runner_arch, runner_image, labels_json, html_url, raw_json, updated_at)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19,
    ?20,
    ?21,
    ?22,
    ?23,
    ?24,
    ?25,
    ?26,
    ?27,
    current_timestamp
)
ON CONFLICT(id) DO UPDATE SET
    run_id = excluded.run_id,
    account = excluded.account,
    repo = excluded.repo,
    repo_owner = excluded.repo_owner,
    repo_owner_kind = excluded.repo_owner_kind,
    billing_owner = excluded.billing_owner,
    billing_owner_kind = excluded.billing_owner_kind,
    billing_plan = excluded.billing_plan,
    cost_class = excluded.cost_class,
    workflow_name = excluded.workflow_name,
    workflow_path = excluded.workflow_path,
    name = excluded.name,
    status = excluded.status,
    conclusion = excluded.conclusion,
    started_at = excluded.started_at,
    completed_at = excluded.completed_at,
    duration_seconds = excluded.duration_seconds,
    runner_name = excluded.runner_name,
    runner_group = excluded.runner_group,
    runner_type = excluded.runner_type,
    runner_os = excluded.runner_os,
    runner_arch = excluded.runner_arch,
    runner_image = excluded.runner_image,
    labels_json = excluded.labels_json,
    html_url = excluded.html_url,
    raw_json = excluded.raw_json,
    updated_at = current_timestamp
`

type UpsertJobParams struct {
	ID               int64
	RunID            sql.NullInt64
	Account          sql.NullString
	Repo             sql.NullString
	RepoOwner        sql.NullString
	RepoOwnerKind    sql.NullString
	BillingOwner     sql.NullString
	BillingOwnerKind sql.NullString
	BillingPlan      sql.NullString
	CostClass        sql.NullString
	WorkflowName     sql.NullString
	WorkflowPath     sql.NullString
	Name             sql.NullString
	Status           sql.NullString
	Conclusion       sql.NullString
	StartedAt        sql.NullString
	CompletedAt      sql.NullString
	DurationSeconds  sql.NullFloat64
	RunnerName       sql.NullString
	RunnerGroup      sql.NullString
	RunnerType       sql.NullString
	RunnerOS         sql.NullString
	RunnerArch       sql.NullString
	RunnerImage      sql.NullString
	LabelsJSON       sql.NullString
	HtmlURL          sql.NullString
	RawJSON          sql.NullString
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertJob,
		arg.ID,
		arg.RunID,
		arg.Account,
		arg.Repo,
		arg.RepoOwner,
		arg.RepoOwnerKind,
		arg.BillingOwner,
		arg.BillingOwnerKind,
		arg.BillingPlan,
		arg.CostClass,
		arg.WorkflowName,
		arg.WorkflowPath,
		arg.Name,
		arg.Status,
		arg.Conclusion,
		arg.StartedAt,
		arg.CompletedAt,
		arg.DurationSeconds,
		arg.RunnerName,
		arg.RunnerGroup,
		arg.RunnerType,
		arg.RunnerOS,
		arg.RunnerArch,
		arg.RunnerImage,
		arg.LabelsJSON,
		arg.HtmlURL,
		arg.RawJSON,
	)
	return err
}

const upsertRepo = `-- name: UpsertRepo :exec
INSERT INTO repos(full_name, id, account, owner, owner_kind, name, private, billing_owner, billing_owner_kind, billing_plan, raw_json, updated_at)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    current_timestamp
)
ON CONFLICT(full_name) DO UPDATE SET
    id = excluded.id,
    account = excluded.account,
    owner = excluded.owner,
    owner_kind = excluded.owner_kind,
    name = excluded.name,
    private = excluded.private,
    billing_owner = excluded.billing_owner,
    billing_owner_kind = excluded.billing_owner_kind,
    billing_plan = excluded.billing_plan,
    raw_json = excluded.raw_json,
    updated_at = current_timestamp
`

type UpsertRepoParams struct {
	FullName         string
	ID               sql.NullInt64
	Account          sql.NullString
	Owner            sql.NullString
	OwnerKind        sql.NullString
	Name             sql.NullString
	Private          sql.NullInt64
	BillingOwner     sql.NullString
	BillingOwnerKind sql.NullString
	BillingPlan      sql.NullString
	RawJSON          sql.NullString
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepo,
		arg.FullName,
		arg.ID,
		arg.Account,
		arg.Owner,
		arg.OwnerKind,
		arg.Name,
		arg.Private,
		arg.BillingOwner,
		arg.BillingOwnerKind,
		arg.BillingPlan,
		arg.RawJSON,
	)
	return err
}

const upsertRun = `-- name: UpsertRun :exec
INSERT INTO runs(id, account, repo, repo_owner, repo_owner_kind, billing_owner, billing_owner_kind, billing_plan, workflow_id, workflow_name, workflow_path, run_number, run_attempt, event, branch, actor, status, conclusion, created_at, run_started_at, html_url, raw_json, updated_at)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18,
    ?19,
    ?20,
    ?21,
    ?22,
    current_timestamp
)
ON CONFLICT(id) DO UPDATE SET
    account = excluded.account,
    repo = excluded.repo,
    repo_owner = excluded.repo_owner,
    repo_owner_kind = excluded.repo_owner_kind,
    billing_owner = excluded.billing_owner,
    billing_owner_kind = excluded.billing_owner_kind,
    billing_plan = excluded.billing_plan,
    workflow_id = excluded.workflow_id,
    workflow_name = excluded.workflow_name,
    workflow_path = excluded.workflow_path,
    run_number = excluded.run_number,
    run_attempt = excluded.run_attempt,
    event = excluded.event,
    branch = excluded.branch,
    actor = excluded.actor,
    status = excluded.status,
    conclusion = excluded.conclusion,
    created_at = excluded.created_at,
    run_started_at = excluded.run_started_at,
    html_url = excluded.html_url,
    raw_json = excluded.raw_json,
    updated_at = current_timestamp
`

type UpsertRunParams struct {
	ID               int64
	Account          sql.NullString
	Repo             sql.NullString
	RepoOwner        sql.NullString
	RepoOwnerKind    sql.NullString
	BillingOwner     sql.NullString
	BillingOwnerKind sql.NullString
	BillingPlan      sql.NullString
	WorkflowID       sql.NullInt64
	WorkflowName     sql.NullString
	WorkflowPath     sql.NullString
	RunNumber        sql.NullInt64
	RunAttempt       sql.NullInt64
	Event            sql.NullString
	Branch           sql.NullString
	Actor            sql.NullString
	Status           sql.NullString
	Conclusion       sql.NullString
	CreatedAt        sql.NullString
	RunStartedAt     sql.NullString
	HtmlURL          sql.NullString
	RawJSON          sql.NullString
}

func (q *Queries) UpsertRun(ctx context.Context, arg UpsertRunParams) error {
	_, err := q.db.ExecContext(ctx, upsertRun,
		arg.ID,
		arg.Account,
		arg.Repo,
		arg.RepoOwner,
		arg.RepoOwnerKind,
		arg.BillingOwner,
		arg.BillingOwnerKind,
		arg.BillingPlan,
		arg.WorkflowID,
		arg.WorkflowName,
		arg.WorkflowPath,
		arg.RunNumber,
		arg.RunAttempt,
		arg.Event,
		arg.Branch,
		arg.Actor,
		arg.Status,
		arg.Conclusion,
		arg.CreatedAt,
		arg.RunStartedAt,
		arg.HtmlURL,
		arg.RawJSON,
	)
	return err
}
